# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en_US"
title                    : "Ingelectus Davsensan"
title_separator          : "&#x7c;"
name                     : "Ingelectus Davsensan"
description              : "We energize the future."
keywords                 : "Ingelectus, Innovative Electrical Solutions, Electric, Electrical Engineering, Charging, Battery, Smartgrids, Electrical Vehicle, EV, Optimization, Forecasting, Energy Consumption Forecasting, State Estimation, CSD, Control Switching Device, Point of Wave, Integration Studies, Electrical Device Modelling, Modelling, PPS/E Model, DigSilent Model, PSCAD Model, ATP Model, Matlab Model, Photovoltaic, PV, Battery Energy Storage System, BESS, Power Plant Controller, PPC, Real Time Thermal Rating, RTTR, Consulting, Renewable, Operation, Solar Plant, Wind Plant, FACTS, Transformer, Inverter, News, Updates, Price, Careers, Jobs"
url                      : "https://davsensan.redirectme.net"
baseurl                  : # default: ""
repository               : # GitHub username/repo-name
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
breadcrumbs              : true # true, false (default)
words_per_minute         : 200
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Organization # Person or Organization (defaults to Person)
  name                   : ingelectus # If the user or organization name differs from the site's name
  links                  : ["https://www.linkedin.com/company-beta/10903835/"] # An array of links to social media profiles

# Analytics
analytics:
  provider               : google # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-52628329

# Site Author
author:
  name             : "Ingelectus"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : 
  location         : 
  email            : 
  uri              : 
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           :
  gitlab           :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/Ingelectus"

# Reading Files
exclude:
  - .asset-cache
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - CHANGELOG
  - LICENSE
  - README.md
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
timezone: Europe/Madrid # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
enconding: utf-8


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /blog/categories/
tag_archive:
  type: liquid
  path: /blog/tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections
collections:
  posts:
    output: true
    layout: post
    permalink: /blog/:title/
    read_time: true
    share: true
    related: true
  pages:
    output: true
  products:
    output: true
    permalink: /products/:name/
  services:
    output: true
    permalink: /services/:name/
  research:
    output: true
    permalink: /research/:name/
  jobs:
    output: true
    permalink: /careers/:name/

github: [metadata]